export type ConfigTypes = {
  NODE_ENV: string;
  PORT: number;
  LOCAL_PORT: number;
  MONGODB_URI: string;
  JWT_SECRET: string;
  REFRESH_TOKEN_SECRET: string;
  EMAIL: string;
  EMAIL_PASSWORD: string;
  EMAIL_SERVICE: string;
  EMAIL_PORT: number;
  EMAIL_HOST: string;
  EMAIL_SECURE: boolean;
  EMAIL_FROM: string;
  CLOUDINARY_NAME: string;
  CLOUDINARY_API_KEY: string;
  CLOUDINARY_SECRET: string;
  BASE_URL: string;
  APP_URL: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  STRIPE_PLATFORM_FEE_PERCENT: number;
};
